import { MailStoreSchema, type MailStore } from "./model";

const personal = {
  id: "acct_personal",
  email: "bea.hart@example.com",
  displayName: "Bea Hart",
  badgeLabel: "Personal",
  enabled: true,
};

const studio = {
  id: "acct_studio",
  email: "bea@stillroom.studio",
  displayName: "Bea at Stillroom",
  badgeLabel: "Studio",
  enabled: true,
};

const ucla = {
  id: "acct_ucla",
  email: "bhart@ucla.edu",
  displayName: "Beatrice Hart",
  badgeLabel: "UCLA",
  enabled: true,
};

const fieldwork = {
  id: "acct_fieldwork",
  email: "bea@fieldwork.co",
  displayName: "Bea Hart",
  badgeLabel: "Fieldwork",
  enabled: true,
};

const rawTestStore = {
  version: 1,
  accounts: [personal, studio, ucla, fieldwork],
  threads: [
    {
      id: "thread_google-interview",
      accountId: personal.id,
      subject: "Interview scheduling update",
      snippet: "Could you send over a few times that work next week? The team is excited to keep things moving.",
      mailbox: "inbox",
      unread: true,
      starred: false,
      lastMessageAt: "2026-08-27T23:41:00.000Z",
      messages: [
        {
          id: "msg_google-interview-1",
          direction: "outgoing",
          from: { name: "Bea Hart", email: personal.email },
          to: [{ name: "Maya Torres", email: "maya@google.com" }],
          cc: [],
          sentAt: "2026-08-25T17:12:00.000Z",
          body: "Hi Maya,\n\nThank you again for the conversation. I enjoyed hearing how the team thinks about calm, dependable product infrastructure.\n\nBest,\nBea",
          attachments: [],
        },
        {
          id: "msg_google-interview-2",
          direction: "incoming",
          from: { name: "Maya Torres", email: "maya@google.com" },
          to: [{ name: "Bea Hart", email: personal.email }],
          cc: [],
          sentAt: "2026-08-27T23:41:00.000Z",
          body: "Hi Bea,\n\nIt was great meeting you too. The team would love to keep things moving. Could you send over a few times that work next week for a 45-minute systems conversation?\n\nMonday afternoon or Wednesday morning would be ideal on our side, but we can make another window work.\n\nWarmly,\nMaya",
          attachments: [],
        },
      ],
    },
    {
      id: "thread_paper-revisions",
      accountId: ucla.id,
      subject: "Paper revisions — Section 4",
      snippet: "I left comments on the transition into Section 4. The argument is there; the framing needs one cleaner pass.",
      mailbox: "inbox",
      unread: true,
      starred: true,
      lastMessageAt: "2026-08-27T22:18:00.000Z",
      messages: [
        {
          id: "msg_paper-revisions-1",
          direction: "incoming",
          from: { name: "Professor Elaine Chen", email: "echen@ucla.edu" },
          to: [{ name: "Beatrice Hart", email: ucla.email }],
          cc: [{ name: "Theo Martin", email: "theomartin@ucla.edu" }],
          sentAt: "2026-08-27T22:18:00.000Z",
          body: "Bea,\n\nI left comments on the transition into Section 4. The argument is there; the framing needs one cleaner pass before we circulate it.\n\nPlease look especially at notes 7–11. If you can return a revision by Friday morning, I can read it before the faculty meeting.\n\nElaine",
          attachments: [{ name: "Hart_Chen_revision-notes.pdf", size: "1.8 MB" }],
        },
      ],
    },
    {
      id: "thread_print-proofs",
      accountId: studio.id,
      subject: "Final print proofs",
      snippet: "The warm stock is the right call. I only caught one issue: the folio on page 18 sits a touch low.",
      mailbox: "inbox",
      unread: false,
      starred: true,
      lastMessageAt: "2026-08-27T20:52:00.000Z",
      messages: [
        {
          id: "msg_print-proofs-1",
          direction: "outgoing",
          from: { name: "Bea at Stillroom", email: studio.email },
          to: [{ name: "Nina Kapoor", email: "nina@kindredpress.com" }],
          cc: [],
          sentAt: "2026-08-26T19:08:00.000Z",
          body: "Nina,\n\nAttaching the latest pass. I pulled the blue back by 6% and let the captions breathe a little more. Let me know what you see on press.\n\nB",
          attachments: [{ name: "stillroom_proof-v7.pdf", size: "12.4 MB" }],
        },
        {
          id: "msg_print-proofs-2",
          direction: "incoming",
          from: { name: "Nina Kapoor", email: "nina@kindredpress.com" },
          to: [{ name: "Bea at Stillroom", email: studio.email }],
          cc: [],
          sentAt: "2026-08-27T20:52:00.000Z",
          body: "The warm stock is the right call. Everything feels much more settled.\n\nI only caught one issue: the folio on page 18 sits a touch low. If you nudge that up, I think we are ready to sign off.\n\n— Nina",
          attachments: [{ name: "page-18-markup.png", size: "684 KB" }],
        },
      ],
    },
    {
      id: "thread_launch-notes",
      accountId: fieldwork.id,
      subject: "Thursday launch notes + owners",
      snippet: "I consolidated the open launch items below. Please reply if any owner or deadline looks wrong.",
      mailbox: "inbox",
      unread: true,
      starred: false,
      lastMessageAt: "2026-08-27T19:27:00.000Z",
      messages: [
        {
          id: "msg_launch-notes-1",
          direction: "incoming",
          from: { name: "Riley Okafor", email: "riley@fieldwork.co" },
          to: [{ name: "Bea Hart", email: fieldwork.email }],
          cc: [
            { name: "Jo Levin", email: "jo@fieldwork.co" },
            { name: "Sana Malik", email: "sana@fieldwork.co" },
          ],
          sentAt: "2026-08-27T19:27:00.000Z",
          body: "Team,\n\nI consolidated the open launch items below. Please reply if any owner or deadline looks wrong.\n\n• Bea — final customer note, Thursday 10:00\n• Jo — status page copy, Thursday 11:30\n• Sana — migration report, Wednesday EOD\n\nWe will use the 9:15 standup as the final go / no-go.\n\nRiley",
          attachments: [{ name: "launch-runbook.xlsx", size: "942 KB" }],
        },
      ],
    },
    {
      id: "thread_amtrak",
      accountId: personal.id,
      subject: "Your trip to Oakland is confirmed",
      snippet: "Coast Starlight 14 departs Los Angeles Union Station at 9:51 AM on Saturday.",
      mailbox: "inbox",
      unread: false,
      starred: false,
      lastMessageAt: "2026-08-27T17:04:00.000Z",
      messages: [
        {
          id: "msg_amtrak-1",
          direction: "incoming",
          from: { name: "Amtrak", email: "reservations@amtrak.com" },
          to: [{ name: "Bea Hart", email: personal.email }],
          cc: [],
          sentAt: "2026-08-27T17:04:00.000Z",
          body: "Your trip is confirmed.\n\nCoast Starlight 14\nLos Angeles Union Station → Oakland Jack London Square\nSaturday, August 29 · 9:51 AM\n\nReservation: 7D4P2A",
          attachments: [{ name: "ticket-7D4P2A.pdf", size: "228 KB" }],
        },
      ],
    },
    {
      id: "thread_gallery-window",
      accountId: studio.id,
      subject: "Window vinyl measurements",
      snippet: "The installer confirmed 94 ⅜ × 61 ½ inches. We need final art by noon tomorrow to keep Monday.",
      mailbox: "inbox",
      unread: true,
      starred: false,
      lastMessageAt: "2026-08-27T15:32:00.000Z",
      messages: [
        {
          id: "msg_gallery-window-1",
          direction: "incoming",
          from: { name: "Luca Greene", email: "luca@noonlight.gallery" },
          to: [{ name: "Stillroom Studio", email: studio.email }],
          cc: [],
          sentAt: "2026-08-27T15:32:00.000Z",
          body: "Hi Bea,\n\nThe installer confirmed 94 ⅜ × 61 ½ inches. We need final art by noon tomorrow to keep Monday's install slot.\n\nThe left edge loses about half an inch behind the mullion, so please keep the date clear of that area.\n\nLuca",
          attachments: [],
        },
      ],
    },
    {
      id: "thread_methods-group",
      accountId: ucla.id,
      subject: "Methods group — room change",
      snippet: "Tomorrow's workshop moved to Public Affairs 2232. Same time, 2–4 PM.",
      mailbox: "inbox",
      unread: false,
      starred: false,
      lastMessageAt: "2026-08-27T13:08:00.000Z",
      messages: [
        {
          id: "msg_methods-group-1",
          direction: "incoming",
          from: { name: "Sociology Methods Group", email: "methods@ucla.edu" },
          to: [{ name: "Beatrice Hart", email: ucla.email }],
          cc: [],
          sentAt: "2026-08-27T13:08:00.000Z",
          body: "Tomorrow's workshop moved to Public Affairs 2232. Same time, 2–4 PM.\n\nWe will discuss field-note coding with a short example from the transit study. Coffee will be outside the room from 1:45.",
          attachments: [],
        },
      ],
    },
    {
      id: "thread_power-bill",
      accountId: personal.id,
      subject: "Your August statement is ready",
      snippet: "Your new statement total is $84.16 and will be paid automatically on September 8.",
      mailbox: "inbox",
      unread: true,
      starred: false,
      lastMessageAt: "2026-08-26T23:10:00.000Z",
      messages: [
        {
          id: "msg_power-bill-1",
          direction: "incoming",
          from: { name: "LADWP", email: "billing@ladwp.com" },
          to: [{ name: "Bea Hart", email: personal.email }],
          cc: [],
          sentAt: "2026-08-26T23:10:00.000Z",
          body: "Your August statement is ready.\n\nAmount due: $84.16\nAutomatic payment date: September 8, 2026\nService address: •••• Bellevue Ave",
          attachments: [{ name: "statement-august.pdf", size: "318 KB" }],
        },
      ],
    },
    {
      id: "thread_field-notes",
      accountId: fieldwork.id,
      subject: "Transit study: field notes batch 06",
      snippet: "Batch 06 is cleaned and ready for your pass. I flagged three entries where the station IDs conflict.",
      mailbox: "archive",
      unread: false,
      starred: false,
      lastMessageAt: "2026-08-25T18:14:00.000Z",
      messages: [
        {
          id: "msg_field-notes-1",
          direction: "incoming",
          from: { name: "Sana Malik", email: "sana@fieldwork.co" },
          to: [{ name: "Bea Hart", email: fieldwork.email }],
          cc: [],
          sentAt: "2026-08-25T18:14:00.000Z",
          body: "Batch 06 is cleaned and ready for your pass. I flagged three entries where the station IDs conflict with the observer sheets.\n\nNo rush before Monday.\n\nSana",
          attachments: [{ name: "batch-06-notes.csv", size: "2.1 MB" }],
        },
      ],
    },
    {
      id: "thread_intro-oliver",
      accountId: studio.id,
      subject: "Re: Intro to Oliver at Vessel",
      snippet: "Thanks for making the introduction. Oliver and I found a time next week.",
      mailbox: "sent",
      unread: false,
      starred: false,
      lastMessageAt: "2026-08-24T19:44:00.000Z",
      messages: [
        {
          id: "msg_intro-oliver-1",
          direction: "outgoing",
          from: { name: "Bea at Stillroom", email: studio.email },
          to: [{ name: "Mina Shah", email: "mina@formlibrary.org" }],
          cc: [{ name: "Oliver Dean", email: "oliver@vessel.work" }],
          sentAt: "2026-08-24T19:44:00.000Z",
          body: "Thanks for making the introduction, Mina. Oliver and I found a time next week.\n\nI will send a few references before we meet.\n\nB",
          attachments: [],
        },
      ],
    },
    {
      id: "thread_old-promo",
      accountId: personal.id,
      subject: "Last chance: summer member sale",
      snippet: "Take an extra 20% off before midnight.",
      mailbox: "trash",
      unread: false,
      starred: false,
      lastMessageAt: "2026-08-22T16:05:00.000Z",
      messages: [
        {
          id: "msg_old-promo-1",
          direction: "incoming",
          from: { name: "Juniper Market", email: "hello@junipermarket.com" },
          to: [{ name: "Bea Hart", email: personal.email }],
          cc: [],
          sentAt: "2026-08-22T16:05:00.000Z",
          body: "Take an extra 20% off before midnight. Online only; exclusions apply.",
          attachments: [],
        },
      ],
    },
  ],
  drafts: [
    {
      id: "draft_gallery-opening",
      accountId: studio.id,
      origin: { kind: "new" },
      to: "Mina Shah <mina@formlibrary.org>",
      cc: "",
      subject: "Stillroom opening — save the date",
      body: "Mina,\n\nWe are opening the new Stillroom space on September 18. I would love for you to come by before the evening gets crowded.\n\n",
      updatedAt: "2026-08-27T18:32:00.000Z",
    },
  ],
  preferences: {
    defaultAccountId: personal.id,
    lastComposeAccountId: studio.id,
  },
};

export const testStore: MailStore = MailStoreSchema.parse(rawTestStore);
